name: Supra-Inventory
version: '${project.version}'
main: fr.chilli.Main
api-version: 1.19
authors: [ Jules ]
description: A complete plugin to allow player to save inventory with a new way of storage with high speed

commands:
  bank:
    description: Send money from your account to your bank
  sb:
    description: scoreboard